name: push-event

on:
  push:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github-actions repo
        uses: actions/checkout@v4
        with:
          repository: aerius/github-actions
          path: aerius-github-actions
          ref: v1.1

      - uses: aerius/github-actions/extras/docker-publish-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}
