name: Publish Docker image

on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get project version
        id: get_project_version
        run: |
          VERSION=$(<VERSION)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - if: github.event_name == 'release' || endsWith(steps.get_project_version.outputs.version, '-SNAPSHOT')
        name: Login to AERIUS Container Registry
        uses: docker/login-action@v1 
        with:
          registry: nexus-docker.aerius.nl
          username: ${{ secrets.nexus_username }}
          password: ${{ secrets.nexus_password }}
      - if: github.event_name == 'release' || endsWith(steps.get_project_version.outputs.version, '-SNAPSHOT')
        name: Build and push images
        run: |
          export DOCKER_REGISTRY_URL=nexus-docker.aerius.nl

          echo '### Building and pushing images ### '
          PUSH_IMAGES=true ./build_images.sh
